
import Header from "../components/layout/header"
import "./globals.css";
import { Roboto } from "next/font/google";
import AppProvider from './AppContext'
import { Toaster } from "react-hot-toast";
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<html lang="en">
      <body className={roboto.className}>
        <AppProvider>
          <Toaster />
          <div className="flex flex-col min-h-screen  max-w-8xl">
            {/* Header */}
            <Header />

            {/* Main Content */}
            <main className="flex-grow max-w-8xl mx-auto px-6 py-4">
              {children}
            </main>

            {/* Footer */}
            <footer className="border-t pt-6 pb-4 text-gray-500 text-center mt-12">
              &copy; 2025 All rights reserved
            </footer>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}